# Pelatihan Dasar Analisis Data Molekuler

## Pendahuluan

Sebagai salah satu kontribusi untuk memberikan akses luas dalam pembelajaran ilmu ekologi molekuler kami bertujuan untuk menyelenggarakan workshop untuk membantu para peneliti mempelajari berbagai keterampilan dasar untuk menganalisis data molekuler. Saat ini penelitian seputar ekologi molekuler memainkan peran penting untuk mendeteksi spesies ataupun hubungan antara spesies dan lokasi dimana spesies tersebut ditemukan. Studi ekologi molekuler juga menjadi bagian yang vital sebagai landasan kebijakan terkait konservasi kawasan ataupun organisme jenis. Namun studi ini masih perlu diperluas lagi pembelajarannya sehingga dapat diimplementasikan secara langsung kepada penggiat, mahasiswa, pengajar ataupun peneliti yang ada di Indonesia. Upaya ini juga dilakukan untuk memahami keanekaragaman hayati dan pemilihan tindakan konservasi yang tepat untuk melindungi biota dan ekosistem.

## Detail Kegiatan

Kegiatan ini akan dilakukan dalam jaringan (daring) melalui aplikasi ZOOM sebanyak empat kali dan setiap pertemuan diadakan 2 minggu sekali; Tanggal 22 Oktober, 5 November, 3 & 17 Desember 2022; 3 jam kegiatan setiap workshop). Kegiatan ini didukung sepenuhnya oleh Code for Science &amp; Society ([https://eventfund.codeforscience.org](https://eventfund.codeforscience.org/)) melalui hibah yang diberikan kepada Yayasan Biodiversitas Indonesia (BIONESIA). Judul dari hibah ini adalah &quot;_Lessening the Gap: Nurturing Access for Young researcher in Eastern Indonesia to Analyze Molecular Data_&quot; dengan tujuan untuk mengadakan workshop tentang dasar-dasar analisis data molekuler. Hibah ini juga merupakan bagian dari _Grant Number GBMF8449 from the Gordon and Betty Moore Foundation (_[_https://doi.org/10.37807/GBMF8449_](https://doi.org/10.37807/GBMF8449)_)._

Kegiatan ini menargetkan total .... orang peserta, dengan sistem rekrutmenterbuka. Peserta yang berminat diharapkan untuk mendaftar dengan mengisi tautan berikut https://bit.ly/WorkshopMolecular, sampai tgl 7 Oktober 22. Peserta yang diterima akan diumumkan pada Kamis, 14 Oktober 2022. Seminggu sebelum kegiatan peserta akan menerima link untuk melihat data, program dan protokol yang harus disiapkan. Peserta diharapkan dapat mengikuti semua rangkaian kegiatan dan mengumpulkan tugas yang diberikan pada akhir kegiatan untuk bisa mendapatkan e-Certificate. Peserta diharapkan memiliki laptop yang dapat mengunduh program seperti MEGA X, R Studio, dan Notepad ++.

Tim pemateri dan pelaksana workshop berasal dari BIONESIA yaitu:

1. Ni Kadek Dita Cahyani, Ph.D.--> Editing Sekuen menggunakan Software MEGA X dan DNA Barcoding
2. Yuliana Fitri Syamsuni, Ph.D.c. --> Genetika Populasi
3. Aji Wahyu Anggoro, Ph.D.c. --> Pengenalan R
4. Eka Maya Kurniasih, M.Si. dan Danie Al Malik, S.Kel. --> Teknis kegiatan dan _contact person_

Pada setiap kegiatan, kami akan mengundang satu pembicara yang merupakan akademisi atau peneliti Indonesia yang berafiliasi dengan perguruan tinggi atau institusi di Indonesia atau luar negeri. Harapannya, akan terjalin komunikasi dan kerjasama untuk penelitian ke depannya.

## Materi Workshop

Workshop ini akan memberikan beberapa keterampilan dasar seputar tahap-tahap yang dibutuhkan untuk menganalisis data molekuler atau sekuen DNA. Materi workshops akan melingkupi dasar-dasar analisis data molekuler yang diawali dengan Editing Sekuen dengan program MEGA X, DNA Barcoding yang meliputi BLAST ke NCBI, Teori tentang Genetika Populasi dan pengenalan tentang bahasa pemrograman R untuk statistik dan visualisasi data. Beberapa teori dan materi workshop akan bisa diunduh melalui tautan yang akan dibagikan seminggu sebelum kegiatan berlangsung, Tautan tersebut juga akan menjadi sumber untuk mengunduh dan memasang program yang dibutuhkan dalam workshop setiap minggunya.

### Susunan Acara

#### Pertemuan pertama, 22 Oktober 2022

| Jam (WITA) | Kegiatan | Keterangan |
| --- | --- | --- |
| 09.00 - 09.15 | Pembukaan |  Perwakilan dari Yayasan Biodiversitas Indonesia, Ni kadek Dita Cahyani, PhD. |
| 09.15 - 09.30 | Pemberitahuan Alur Kegiatan | Dipandu moderator (Eka Maya Kurniasih dan Danie Al Malik) |
| 09.30 - 10.00 | Invited Speaker 1 | Dr. Nur Fadli (UNSIYAH) |
| 10.00 - 11.30 | Editing Sekuen dengan MEGA X | Ni Kadek Dita Cahyani, Ph.D. |
| 11.30 - 12.00 | Tanya Jawab | Dipandu moderator (Eka Maya Kurniasih dan Danie Al Malik) |

#### Pertemuan ke-2, 5 November 2022

| Jam (WITA) | Kegiatan | Keterangan |
| --- | --- | --- |
| 09.00 - 09.15 | Pre-Test | Dipandu moderator (Eka dan Danie) |
| 09.15 - 09.45 | Invited Speaker 2 | ??????? |
| 09.45 - 11.30 | DNA Barcoding | Ni Kadek Dita Cahyani, Ph.D. |
| 11.30 - 12.00 | Tanya Jawab | Dipandu moderator (Eka Maya Kurniasih dan Danie Al Malik) |

#### Pertemuan ke-3, 3 Desember 2022

| Jam (WITA) | Kegiatan | Keterangan |
| --- | --- | --- |
| 09.00 - 09.15 | Pre-Test | Dipandu moderator (Eka dan Danie) |
| 09.15 - 09.45 | Invited Speaker 3 | ?????? |
| 09.45 - 11.30 | Genetika Populasi | Yuliana Fitri Syamsuni, Ph.D.c. |
| 11.30 - 12.00 | Tanya Jawab | Dipandu moderator (Eka Maya Kurniasih dan Danie Al Malik) |

#### Pertemuan ke-4, 17 Desember 2022

| Jam (WITA) | Kegiatan | Keterangan |
| --- | --- | --- |
| 09.00 - 09.15 | Pre-Test | Dipandu moderator (Eka dan Danie) |
| 09.15 - 09.45 | Invited Speaker 4 | ?????? |
| 09.45 - 11.30 | Pengenalan R | Aji Wahyu Anggoro, Ph.D.c. |
| 11.30 - 11.50 | Tanya Jawab, Kesan dan Pesan | Dipandu moderator (Eka Maya Kurniasih dan Danie Al Malik) |
| 11.50 - 12.00 | Penutup | Ditutup oleh Direktur Yayasan Biodiversitas Indonesia, Andrianus Sembiring, M.Si. |


###  Hak Cipta

Segala informasi dan material yang kami berikan disini dilisensi oleh Creative Commons Attribution-Share Alike 4.0 International (CC BY-SA 4.0). (CC BY-SA 4.0) Detail tentang hak cipta dapat dilihat di akses di https://creativecommons.org/licenses/by-sa/4.0/deed.id

### Nara Hubung

- Eka Maya Kurniasih (WA: +6281368863448)
- Danie Al Malik (WA: +6287875554365)
- Email : ekamayakurniasih@gmail.com